language: python
python:
  - "3.5"
os:
  - linux
#  - osx   # remove this since travis doesn't support osx for Python 3.5
# command to install dependencies
install: "pip install -r requirements.txt"
# command to run tests
before_script: cd tests
script: ./test_master.sh
