addons:
  ssh_known_hosts:
    - 127.0.0.1
    - localhost
  apt:
    packages:
    - openssh-server

language: python
python:
  - "3.5"
os:
  - linux
#  - osx   # remove this since travis doesn't support osx for Python 3.5
# command to install dependencies
install:
    - "mkdir -p ~/.ssh && chmod 700 ~/.ssh"
    - "ssh-keygen -t rsa -f ${HOME}/.ssh/id_rsa -q -P \"\""
    - "cat ~/.ssh/id_rsa.pub >> ~/.ssh/authorized_keys"
    - "pip install -r requirements.txt"
    - pip install coveralls
# command to run tests
before_script:
  - cd tests
  - export PYTHONPATH=$PYTHONPATH:$(pwd)/..
script: coverage run --source=datasmart -m unittest discover
after_success:
  coveralls
